services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wazum\CrossDomainPreview\:
    resource: '../Classes/*'

  cache.cross_domain_preview:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['cross_domain_preview']
